### PR TITLE
Ads

### PR DESCRIPTION
**Pull request by hostedposted**
Add ads.

### CODE REVIEW

**Comment by afkvido** [comment]
Why ProdigyPNP is better.

**Comment by hostedposted** [comment]
ProdigyPNP does not have hacks that are as good, like ``Find User Id of People on Screen``, ``Complete Rune Run``, ``Alt Account Generator`` and ``Duplicate Account``

**Comment by afkvido** [comment]
ProdigyPNP does have Find UserIDs, but it is true that we dont't have those other 3.

and at least we dont have **FUCKING ADS LMAO**

**Comment by hostedposted** [comment]
Seriously, you stole our hack?!

**Comment by afkvido** [comment]
I copied no code at all from you.

**Comment by AgrTheDev** [comment]
Dude, why are you here first of all. I left you alone knowing that you and "your" (I can't even call it your own as you don't know how PNP works lol.) shitty menu would be as far away from us as possible. And now here you are. You are only against ads because you didn't put any actual effort into your menu and therefor your labor isn't valued like ours. I can't even express my hate for you. The only one on PNP who actually gets on my nerves. You are a racist 11 year old dyed haired weirdo emo with no programming experience whatsoever and only carried by Eris. I left you alone despite feeling bad for you and your brainwashed members into thinking that making sites with animal porn was okay and saying the n slur. You decided to come back so it had to be said.

**Comment by afkvido** [comment]
lmao

**Comment by Erisfiregamer1** [comment]
> Dude, why are you here first of all. I left you alone knowing that you and "your" (I can't even call it your own as you don't know how PNP works lol.) shitty menu would be as far away from us as possible. And now here you are. You are only against ads because you didn't put any actual effort into your menu and therefor your labor isn't valued like ours. I can't even express my hate for you. The only one on PNP who actually gets on my nerves. You are a racist 11 year old dyed haired weirdo emo with no programming experience whatsoever and only carried by Eris. I left you alone despite feeling bad for you and your brainwashed members into thinking that making sites with animal porn was okay and saying the n slur. You decided to come back so it had to be said.

Mostly valid claims here, but:
- I know barely anything about programming. My only existence in ProdigyPNP as of current is to stop it from exploding and help Svido from time to time with things that I WOULD know. And hosting 2 of the PNP servers.

**Comment by afkvido** [comment]
xd

**Pull request merged**
